### ISSUE TITLE
Errors not sent when providing an API key only

### ISSUE THREAD

**Issue by steren** [GoogleCloudPlatform/cloud-errors-nodejs#10]
- I ran `export NODE_ENV=production`
- I installed express and cloud-errors.
- I run the following code:

I could not see errors in the Error Reporting UI for this project.
I could successfully send manually errors to this project with this API key (by calling the API from cURL).

```
var express = require('express');
var app = express();
var errorHandler = require('@google/cloud-errors')({
  projectId: "<my project>",
  key: "<my api key>",
  serviceContext: {
      service: 'steren-test-node',
      version: 'test1'
  }
});

app.get(
  '/errorRoute',
  function ( req, res, next ) {
    // You can push in errors manually
    res.send("Error");
    res.end();
    next(new Error("Got traffic on the errorRoute"));
  }
);

app.get(
  '/anotherRoute',
  function ( req, res, next ) {
    // It'll even log potentially unexpected errors
    JSON.parse("{\"malformedJson\": true");
  }
)

// Just use the express plugin
app.use(errorHandler.express);

app.listen(
  3000
  , function ( ) {
    console.log('Server has been started on port 3000');
  }
);
```

**Comment by steren** [comment]
I now tested the module with Vanilla Node.js:

I ran `export NODE_ENV=production`

My code:
```
var errorHandler = require('@google/cloud-errors')({
    projectId: '<project id>',
    key: '<valid API key>'
});

errorHandler.report(
    new Error('This is a test'),
    (err, res) => {

        if (err) {
            console.log('Error was unable to be reported', err);
        } else {
            console.log('Error reported!', res);
        }
    }
);
```

I get this error:

>  $ node index.js
> Error was unable to be reported { [Error: Stackdriver Error Reporting API has not been used in project usable-auth-library before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/clouderrorreporting.googleapis.com/overview?project=usable-auth-library then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.]
>   code: 403,
>   errors:
>    [ { message: 'Stackdriver Error Reporting API has not been used in project usable-auth-library before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/clouderrorreporting.googleapis.com/overview?project=usable-auth-library then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.',
>        domain: 'global',
>        reason: 'forbidden' } ] }

Note that my project is **not** named `usable-auth-library` but `grimm-git`

**Comment by cristiancavalli** [comment]
@steren This is really weird.
I copied and pasted this exact example into a fresh project using the lib and got success statuses for the express and manual examples. Do you have any other project env data referring to this usable-auth-library project. The supplied arguments should override this, just trying to figure where its coming from if its a fault with the lib

**Comment by ofrobots** [comment]
I got the same error about `usable-auth-library` on my own app:

```
Error: Stackdriver Error Reporting API has not been used in project usable-auth-library before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/clouderrorreporting.googleapis.com/overview?project=usable-auth-library then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.
```

This happens when I provided a projectId, but no key or keyFile. I wonder if the error message is from the Application Default Credentials trying to fallback to the `gcloud beta application-default` login credentials. See: https://developers.google.com/identity/protocols/application-default-credentials.

**Comment by cristiancavalli** [comment]
reproduced, triaging

**Comment by ofrobots** [comment]
I am pretty sure that this is due to application default credentials. There are two fixes needed:

* I think google-auth-library is using application-default-credentials instead of the provided key string. We should figure out a solution here. [AI: @cristiancavalli]
* The Error reporting API should accept application default credentials. We had the same issue with the trace agent before until they got their api white-listed to be able to accept application default credentials. [AI: @steren, we can discuss this offline].

**Comment by steren** [comment]
@ofrobots OK, I assumed it was already the case, sorry. I created an internal bug (http://b/30242004) to track the request.

**Comment by steren** [comment]
Also, I think the error message returned by google-auth-library is very misleading. Shall I open an issue for it?

**Comment by JustinBeckwith** [comment]
This also came up at NodeSummit while we were prepping for the demo.

**Comment by cristiancavalli** [comment]
This is block by https://github.com/google/google-auth-library-nodejs/pull/92

**Comment by cristiancavalli** [comment]
Will add to errors when bandwidth is available

**Comment by ofrobots** [comment]
@cristiancavalli What is the status of this?

**Comment by cristiancavalli** [comment]
Status is the same since we are blocked bythe Google auth library allowing
us to use API keys in place of key files

**Comment by steren** [comment]
The module is still not working with API keys.
I ran the following:
```js
var errors = require('@google/cloud-errors').start({
    projectId: '<my-project>',
    key: '<my-api-key>',
    serviceContext: {service: 'my-service'}
});
errors.report(new Error('Something broke!'));
```
And I get nothing in the Error Reporting UI or in my application output.

We should update the README to remove the API key instructions, if we know it is not working at the moment.

**Comment by cristiancavalli** [comment]
Tentatively re-adding the blocked label since this was removed by myself in error

**Comment by cristiancavalli** [comment]
@steren So that we're all on the same page:

This library supports the key field and appends it to the url, see https://github.com/GoogleCloudPlatform/cloud-errors-nodejs/blob/master/lib/google-apis/auth-client.js#L73

I tried your test with a new api key myself and it failed, so this does not seem to be a failing on the part of the library unless were are composing the url incorrectly in which case the API explorer is also wrong. Here is a sample from the lib and thusly from the API Explorer:
`https://clouderrorreporting.googleapis.com/v1beta1/projects/{project-id}/events:report?key={YOUR_API_KEY}`

I'm not sure if the endpoint needs to be updated or we need to send a different param/header.

cc @ofrobots

**Comment by steren** [comment]
This API endpoint is used by many external users every day. I am also using it regularly for testing. I confirm that the API endpoint works.

For example, this command is working, you can use it for testing:
```
curl -X POST -H "Content-Type: application/json" \
  -d '{"message":"java.lang.TestError: msg\n\tat com.example.TestClass.test(TestClass.java:51)\n\tat com.example.AnotherClass(AnotherClass.java:25)","serviceContext":{"service":"manual-testing"}}' \
  https://clouderrorreporting.googleapis.com/v1beta1/projects/PROJECT_ID/events:report?key=API_KEY
```

Are you sending the `Content-Type: application/json` header?

**Comment by steren** [comment]
Also, if the library fails to report the error (like in this case), I would expect it to print something in the console. Is it the case?

**Comment by DominicKramer** [comment]
This issue has been closed since it is now being tracked in the [google-cloud-node/error-reporting](https://github.com/GoogleCloudPlatform/google-cloud-node/tree/master/packages/error-reporting) repository under issue [#2302](https://github.com/GoogleCloudPlatform/google-cloud-node/issues/2302).
