### ISSUE TITLE
Uncaught exception handler should terminate with a timeout

### ISSUE THREAD

**Issue by ofrobots** [GoogleCloudPlatform/cloud-errors-nodejs#35]
```JS
function uncaughtExceptionHandler(client, config, err) {
  var em = new ErrorMessage();

  errorHandlerRouter(err, em);

  client.sendError(em, handleProcessExit);
}
```

If things are completely b0rked, `sendError` might never succeed, in which case process may never exit. I think we should follow a policy similar to the trace agent where we expose a delay in the config after which we terminate the process regardless. WDYT?
/cc @matthewloring

**Comment by cristiancavalli** [comment]
@matthewloring @ofrobots I propose a 1.5 second timeout, thoughts?

**Comment by matthewloring** [comment]
Sorry I missed this. The trace agent currently does a 2 second delay (unconfigurable). I don't have a strong preference on the default value of this. 1 second should be sufficient for publishing if the world is in a sane state so anything higher than that is fine. I'm not sure whether we need the delay to be configurable because if the two second delay is insufficient then there must be other work being done in which case the end user could set the configuration option to `flush` and handle process exit after the other work has completed.
