### ISSUE TITLE
Users can choose to report errors via Logs instead of using the report API

### ISSUE THREAD

**Issue by steren** [GoogleCloudPlatform/cloud-errors-nodejs#48]
_This is an enhancement that should not be blocking the Beta launch of this module._

We can send errors to Error Reporting by calling the [report API endpoint](https://cloud.google.com/error-reporting/reference/rest/v1beta1/projects.events/report) or by logging errors in Stackdriver Logging using [the appropriate structured format](https://cloud.google.com/error-reporting/docs/formatting-error-messages).

Today, cloud-errors-nodejs reports errors using the API endpoint.
This is a great default choice as it does not require any additional setup than enabling the API and do not forces to use Stackdriver Logging.

However, if users want to use Stackdriver Logging for application logging, it is better to capture logs and errors using the same mechanism, so that they can see errors in the Logs viewer too.

Users should be able to chose to report errors via Logs. We could imagine that when initializing this module, they can pass a logger that will be used to log errors.

**Comment by JustinBeckwith** [comment]
It doesn't sound like this is a feature request for this npm module, is it?  A change like that would have to be supported from the logging back end.... right?

**Comment by steren** [comment]
The logging backend does support it already. Any exception logged in the [appropriate structured format](https://cloud.google.com/error-reporting/docs/formatting-error-messages) will be picked up by Error Reporting.

What we need to do, is a simple way for users of this module to declare that they prefer reporting errors via a given logger rather that the API.

**Comment by matthewloring** [comment]
Does the log viewer provide any capability that the error UI does not? If errors are already visualized elsewhere duplicating them in the logs could make the logs more difficult to dig through when looking for specific information.

**Comment by steren** [comment]
It is not a matter of duplication or UI capabilities. It is a matter of choosing an ingestion method for Error Reporting.

The API ingestion method has benefits (easy setup and not counting toward Logging quota), but also drawbacks: not all errors are retained, no export to BigQuery, no batching of queries...

Furthermore, some users just want to see their errors in their logs too.

The log ingestion method is how it works on GAE standard and on other places were we have an out of the box support.

**Comment by JustinBeckwith** [comment]
Got it.  I think this is something we should try to address *after* we get the cloud logging npm module out.

**Comment by steren** [comment]
Totally. And definitely not a blocker for releasing this module to Beta.

**Comment by ofrobots** [comment]
Let me summarize the pros/cons. Let me know if I misunderstood anything.

Benefits of sending the message through the logging API:
* The Error Reporting API isn't enabled by default today and users have to manually enable it. (But this is going to fixed in the future).
* It would be nice if the errors show up in the log stream too. If we send errors via the REST API endpoint, they would only show up in error reporting.
* Errors Rest API doesn't have the same retention, ability to export to BigQuery, batching.

There are some complexities with making this work with the logging API:
* This should only be done if this does not involve adding a dependency on `@google-cloud/logging` (and transitively `grpc`). Having a dependency on `grpc` would increase friction to users and makes this module usable to fewer people.
* Errors would count against the logging quota.
* Users may not be using `@google-cloud/logging` directly. They may be using some higher level layers (e.g. logging-bunyan, logging-winston).
* If the users are using logging-winston or logging-bunyan, we should already be able to format the users' error message to allow Error Reporting to pick them up.

To conclude, I think, this makes sense to do only if the user is using `@google-cloud/logging` directly and not a higher level use-case. I don't expect that to be a common use-case, for it to be worth implementing here.

Thoughts?

**Comment by steren** [comment]
+1 to your suggestion.

The main goal is indeed that Stackdriver Logging users should be able to capture their errors in Logs.

**Comment by DominicKramer** [comment]
This issue has been closed since it is now being tracked in the [google-cloud-node/error-reporting](https://github.com/GoogleCloudPlatform/google-cloud-node/tree/master/packages/error-reporting) repository under issue [#2301](https://github.com/GoogleCloudPlatform/google-cloud-node/issues/2301).
